"""initial domain schema

Crea las 7 tablas del dominio: types y type_effectiveness (matriz 18x18),
pokemon y pokemon_types (N:M con slot), teams y team_members, y
optimization_runs con los parametros en JSONB.

Revision ID: b82936a79b08
Revises:
Create Date: 2026-08-26 12:35:18.213266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b82936a79b08"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pokeapi_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=True),
        sa.Column("is_legendary", sa.Boolean(), nullable=False),
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Integer(), nullable=False),
        sa.Column("defense", sa.Integer(), nullable=False),
        sa.Column("sp_attack", sa.Integer(), nullable=False),
        sa.Column("sp_defense", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("bst", sa.Integer(), nullable=False),
        sa.Column("sprite_url", sa.String(length=255), nullable=True),
        sa.Column("artwork_url", sa.String(length=255), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("bst > 0", name=op.f("ck_pokemon_ck_pokemon_bst_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pokemon")),
    )
    op.create_index("ix_pokemon_bst", "pokemon", ["bst"], unique=False)
    op.create_index(op.f("ix_pokemon_name"), "pokemon", ["name"], unique=True)
    op.create_index(op.f("ix_pokemon_pokeapi_id"), "pokemon", ["pokeapi_id"], unique=True)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_created_at"), "teams", ["created_at"], unique=False)
    op.create_index(op.f("ix_teams_kind"), "teams", ["kind"], unique=False)
    op.create_table(
        "types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_types")),
    )
    op.create_index(op.f("ix_types_name"), "types", ["name"], unique=True)
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rival_team_id", sa.Integer(), nullable=False),
        sa.Column("result_team_id", sa.Integer(), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=False),
        sa.Column("coverage_pct", sa.Float(), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.String(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "coverage_pct BETWEEN 0 AND 100",
            name=op.f("ck_optimization_runs_ck_optimization_runs_coverage"),
        ),
        sa.CheckConstraint(
            "elapsed_ms >= 0", name=op.f("ck_optimization_runs_ck_optimization_runs_elapsed")
        ),
        sa.ForeignKeyConstraint(
            ["result_team_id"],
            ["teams.id"],
            name=op.f("fk_optimization_runs_result_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rival_team_id"],
            ["teams.id"],
            name=op.f("fk_optimization_runs_rival_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_runs")),
    )
    op.create_index(
        op.f("ix_optimization_runs_algorithm"), "optimization_runs", ["algorithm"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_runs_created_at"), "optimization_runs", ["created_at"], unique=False
    )
    op.create_table(
        "pokemon_types",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.CheckConstraint("slot IN (1, 2)", name=op.f("ck_pokemon_types_ck_pokemon_types_slot")),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
            name=op.f("fk_pokemon_types_pokemon_id_pokemon"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["types.id"],
            name=op.f("fk_pokemon_types_type_id_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pokemon_id", "type_id", name=op.f("pk_pokemon_types")),
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "slot BETWEEN 1 AND 6", name=op.f("ck_team_members_ck_team_members_slot")
        ),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
            name=op.f("fk_team_members_pokemon_id_pokemon"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_members_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_id", "slot", name=op.f("pk_team_members")),
        sa.UniqueConstraint("team_id", "pokemon_id", name="uq_team_members_no_duplicates"),
    )
    op.create_table(
        "type_effectiveness",
        sa.Column("attacking_type_id", sa.Integer(), nullable=False),
        sa.Column("defending_type_id", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "multiplier IN (0, 0.5, 1, 2)",
            name=op.f("ck_type_effectiveness_ck_type_effectiveness_multiplier"),
        ),
        sa.ForeignKeyConstraint(
            ["attacking_type_id"],
            ["types.id"],
            name=op.f("fk_type_effectiveness_attacking_type_id_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["defending_type_id"],
            ["types.id"],
            name=op.f("fk_type_effectiveness_defending_type_id_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attacking_type_id", "defending_type_id", name=op.f("pk_type_effectiveness")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("type_effectiveness")
    op.drop_table("team_members")
    op.drop_table("pokemon_types")
    op.drop_index(op.f("ix_optimization_runs_created_at"), table_name="optimization_runs")
    op.drop_index(op.f("ix_optimization_runs_algorithm"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    op.drop_index(op.f("ix_types_name"), table_name="types")
    op.drop_table("types")
    op.drop_index(op.f("ix_teams_kind"), table_name="teams")
    op.drop_index(op.f("ix_teams_created_at"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_pokemon_pokeapi_id"), table_name="pokemon")
    op.drop_index(op.f("ix_pokemon_name"), table_name="pokemon")
    op.drop_index("ix_pokemon_bst", table_name="pokemon")
    op.drop_table("pokemon")
    # ### end Alembic commands ###
